
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WareHouseManagement.Models
{

using System;
    using System.Collections.Generic;
    
public partial class InputInfo
{

    public string Id { get; set; }

    public string IdObject { get; set; }

    public string IdInput { get; set; }

    public Nullable<int> Count { get; set; }

    public Nullable<double> InputPrice { get; set; }

    public Nullable<double> OutputPrice { get; set; }

    public string Status { get; set; }



    public virtual Input Input { get; set; }

    public virtual Object Object { get; set; }

}

}
