
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WareHouseManagement.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Object
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Object()
    {

        this.InputInfoes = new HashSet<InputInfo>();

        this.OutputInfoes = new HashSet<OutputInfo>();

    }


    public string Id { get; set; }

    public string DisplayName { get; set; }

    public int IdUnit { get; set; }

    public int IdSupplier { get; set; }

    public string QRCode { get; set; }

    public string BarCode { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<InputInfo> InputInfoes { get; set; }

    public virtual Supplier Supplier { get; set; }

    public virtual Unit Unit { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OutputInfo> OutputInfoes { get; set; }

}

}
