
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WareHouseManagement.Models
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public int Id { get; set; }

    public string DisplayName { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public int IdRole { get; set; }



    public virtual UserRole UserRole { get; set; }

}

}
